/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vmc_serialport_SerialPort */

#ifndef _Included_vmc_serialport_SerialPort
#define _Included_vmc_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vmc_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_vmc_serialport_SerialPort_open
        (JNIEnv *env, jclass thiz, jstring path, jint baudrate, jint stopBits,
                jint dataBits, jint parity, jint flowCon);

/*
 * Class:     vmc_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vmc_serialport_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
